# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
    -   id: pretty-format-java
        args: [--autofix, --aosp, --google-java-formatter-version=1.16.0]
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
