server:
    port: 8181
spring:
    dataSource:
        url: jdbc:postgresql://proxy-db:5432/proxies
        driverClassName: org.postgresql.Driver
        username: postgres_proxy
        password: postgres_proxy_pass
    jpa:
        hibernate:
            ddlAuto: update
        showSql: false
    properties:
        hibernate:
            dialect: org.postgresql.Driver
            format_sql: true
        database: postgresql
        databasePlatform: org.hibernate.dialect.PostgreSQLDialect

url:
    start:
        proxy: https://www.proxy-list.download/api/v1/get?type=https&country=
