server:
  port: 8081
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  dataSource:
    url: jdbc:postgresql://localhost:5432/proxies
    driverClassName: org.postgresql.Driver
    username: postgres_proxy
    password: postgres_proxy_pass
  jpa:
    hibernate:
      dialect: org.postgresql.Driver
      ddlAuto: update
    showSql: false
  properties:
    hibernate:
      format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

url:
  start:
    proxy: https://www.proxy-list.download/api/v1/get?type=https&country=


# proces sprawdzania np co pol godziny czy proxy są git i oflagować np
# selenium - jak strona dynamiczna
# twitter scrapowac walla i po tagach ogarniac ogarniac ?
